# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lc.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import os
import re
import sys
import time
import json
import threading
from config.sql import *
from PyQt5.QtGui import *
from PyQt5.QtCore import *
from fastapi import FastAPI
from PyQt5.QtWidgets import *
from collections import defaultdict
from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWebChannel import QWebChannel
from PyQt5.QtWebEngineWidgets import QWebEngineView
from PyQt5.QtWidgets import QApplication, QWidget,QStackedLayout


app = FastAPI()

class Worker(QThread, QObject):
    breakSignals = pyqtSignal(list)

    def __init__(self,tag =None):
        QObject.__init__(self)
        super(Worker, self).__init__()
        self.Flag = True
        self.tag =tag
        self.start_date =''
        self.end_date =''
        self.data =''

    def run(self):
        while (True):
            if (not self.Flag):
                break
            else:
                print('thread'+str(self.tag)+' is running')
                if self.tag ==3:
                    session3 = MySession()
                    result = chart1(session3,self.data,self.start_date,self.end_date)
                    result1 = chart2(session3,self.data,self.start_date,self.end_date)
                    session3.close()
                    series = [result, result1]
                    self.breakSignals.emit(series)
                    time.sleep(5)

    def setFlag(self, parm):
        self.Flag = parm


class Print(QObject):
    changeList = pyqtSignal(list)

    @pyqtSlot(list, result=list)
    def print(self, content):
        self.changeList.emit(content)
        return content


class Print1(QObject):
    changeList1 = pyqtSignal(list)

    @pyqtSlot(list, result=list)
    def print(self, content):
        self.changeList1.emit(content)
        return content


class Print2(QObject):
    changeList2 = pyqtSignal(list)

    @pyqtSlot(list, result=list)
    def print(self, content):
        self.changeList2.emit(content)
        return content


class Print3(QObject):
    changeList3 = pyqtSignal(list)

    @pyqtSlot(list, result=list)
    def print(self, content):
        self.changeList3.emit(content)
        return content


class A(object):
    def setupUi(self, Form):
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout = QtWidgets.QGridLayout()
        self.label = QtWidgets.QLabel(Form)
        self.label.setStyleSheet("background-color: rgb(0, 0, 0);border: 0px solid #EDEDED;border-radius: 5px")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setStyleSheet("background-color: rgb(0, 0, 0);border: 0px solid #EDEDED;border-radius: 5px")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setStyleSheet("background-color: rgb(0, 0, 0);border: 0px solid #EDEDED;border-radius: 5px")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setStyleSheet("background-color: rgb(0, 0, 0);border: 0px solid #EDEDED;border-radius: 5px")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setStyleSheet("background-color: rgb(0, 0, 0);border: 0px solid #EDEDED;border-radius: 5px")
        self.gridLayout.addWidget(self.label_5, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setStyleSheet("background-color: rgb(0, 0, 0);border: 0px solid #EDEDED;border-radius: 5px")
        self.gridLayout.addWidget(self.label_6, 1, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))


class B(object):
    def setupUi(self, Form):
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.widget = QtWidgets.QWidget()
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.tab1 = QWebEngineView(self.widget)
        self.channel = QWebChannel()
        self.printer = Print()
        self.printer.changeList.connect(self.getchange)
        self.channel.registerObject('printer', self.printer)
        self.tab1.page().setWebChannel(self.channel)
        self.tab1.load(QUrl("file:///./home.html"))
        self.gridLayout_2.addWidget(self.tab1, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))

    #图表模糊搜索
    def getchange(self,e):
        form.t1.data =e[0]
        if e[1] =='' or e[1] ==None:
            form.t1.start_date =''
            form.t1.end_date =''
        else:
            date1 = datetime.datetime.strptime(e[1][0], "%Y-%m-%dT%H:%M:%S.%fZ")
            date2 = datetime.datetime.strptime(e[1][1], "%Y-%m-%dT%H:%M:%S.%fZ")
            form.t1.start_date =date1 + datetime.timedelta(days=1)
            form.t1.end_date =date2 + datetime.timedelta(days=1)


class C(object):
    type=''
    def setupUi(self, Form):
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.widget = QtWidgets.QWidget()
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.tab2 = QWebEngineView(self.widget)
        self.channel1 = QWebChannel()
        self.printer1 = Print1()
        self.printer1.changeList1.connect(self.get_his)
        self.channel1.registerObject('printer1', self.printer1)
        self.tab2.page().setWebChannel(self.channel1)
        self.tab2.load(QUrl("file:///./history.html"))
        self.gridLayout_2.addWidget(self.tab2, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))

    #获取历史记录
    def get_his(self,e):
        session = MySession()
        if e[1] =='' or e[1] ==None:
            lists = session.query(History).filter(History.standard_name.like("%" + e[0]+ "%"),History.types.like("%" + self.type + "%")).order_by(History.id.desc()).limit(2000)
        else:
            date1 = datetime.datetime.strptime(e[1][0], "%Y-%m-%dT%H:%M:%S.%fZ")+ datetime.timedelta(days=1)
            date2 = datetime.datetime.strptime(e[1][1], "%Y-%m-%dT%H:%M:%S.%fZ")+ datetime.timedelta(days=1)
            target_res = date1.strftime("%Y-%m-%d")
            today = date2.strftime("%Y-%m-%d")
            lists = session.query(History).filter(History.standard_name.like("%" + e[0] + "%"),History.types.like("%" + self.type + "%"),History.created_time.between(target_res,today)).order_by(History.id.desc()).limit(2000)
        lists = [x.to_dict() for x in lists]
        session.close()
        self.tab2.page().runJavaScript("window.uptext('{}')".format(json.dumps(lists)))


class D(object):
    def setupUi(self, Form):
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.widget = QtWidgets.QWidget()
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.tab3 = QWebEngineView(self.widget)
        self.channel3 = QWebChannel()
        self.printer3 = Print3()
        # self.printer3.changeList3.connect(self.getrank)
        self.channel3.registerObject('printer3', self.printer3)
        self.tab3.page().setWebChannel(self.channel3)
        self.tab3.load(QUrl("file:///./ranking.html"))
        self.gridLayout_2.addWidget(self.tab3, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))


class E(object):
    image=''
    def setupUi(self, Form):
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout = QtWidgets.QGridLayout()
        self.label = QtWidgets.QLabel(Form)
        self.label.setMinimumSize(QtCore.QSize(100, 60))
        self.label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setMinimumSize(QtCore.QSize(750, 0))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);border: 1px solid rgb(200, 200, 200);")
        self.gridLayout.addWidget(self.label_2, 3, 2, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, -1, -1, 0)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.clicked.connect(self.openfile)
        self.pushButton_2.setMinimumSize(QtCore.QSize(200, 90))
        self.pushButton_2.setMaximumSize(QtCore.QSize(450, 16777215))
        self.pushButton_2.setStyleSheet("QPushButton\n"
                                        "                    {text-align : center;\n"
                                        "                     color:gray;\n"
                                        "                     font: bold;\n"
                                        "                     border-radius:10px;\n"
                                        "                     border-top-color: #888888;\n"
                                        "                     border-left-color: #888888;\n"
                                        "                     border-right-color: #CCCCCC;\n"
                                        "                     border-bottom-color: #CCCCCC;\n"
                                        "                     border-top-width:2px;\n"
                                        "                     border-left-width:3px;\n"
                                        "                     border-right-width:3px;\n"
                                        "                     border-bottom-width:4px;\n"
                                        "                     border-style: outset;\n"
                                        "                     font : 14px;}\n"
                                        "                     QPushButton:pressed\n"
                                        "                     {text-align : center;\n"
                                        "                      background-color : light gray;\n"
                                        "                      font: bold;\n"
                                        "                      border-top-color: #888888;\n"
                                        "                      border-left-color: #888888;\n"
                                        "                      border-right-color: #CCCCCC;\n"
                                        "                      border-bottom-color: #CCCCCC;\n"
                                        "                      border-width: 2px;\n"
                                        "                      border-style: outset;\n"
                                        "                      font : 14px;}\n"
                                        "\n"
                                        "")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setMinimumSize(QtCore.QSize(200, 90))
        self.pushButton_3.setMaximumSize(QtCore.QSize(450, 16777215))
        self.pushButton_3.setStyleSheet("QPushButton\n"
                                        "                    {text-align : center;\n"
                                        "                     color:gray;\n"
                                        "                     font: bold;\n"
                                        "                     border-radius:10px;\n"
                                        "                     border-top-color: #888888;\n"
                                        "                     border-left-color: #888888;\n"
                                        "                     border-right-color: #CCCCCC;\n"
                                        "                     border-bottom-color: #CCCCCC;\n"
                                        "                     border-top-width:2px;\n"
                                        "                     border-left-width:3px;\n"
                                        "                     border-right-width:3px;\n"
                                        "                     border-bottom-width:4px;\n"
                                        "                     border-style: outset;\n"
                                        "                     font : 14px;}\n"
                                        "                     QPushButton:pressed\n"
                                        "                     {text-align : center;\n"
                                        "                      background-color : light gray;\n"
                                        "                      font: bold;\n"
                                        "                      border-top-color: #888888;\n"
                                        "                      border-left-color: #888888;\n"
                                        "                      border-right-color: #CCCCCC;\n"
                                        "                      border-bottom-color: #CCCCCC;\n"
                                        "                      border-width: 2px;\n"
                                        "                      border-style: outset;\n"
                                        "                      font : 14px;}\n"
                                        "\n"
                                        "")
        self.verticalLayout.addWidget(self.pushButton_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.clicked.connect(self.ok)
        self.pushButton.setMinimumSize(QtCore.QSize(200, 90))
        self.pushButton.setMaximumSize(QtCore.QSize(450, 16777215))
        self.pushButton.setStyleSheet("QPushButton\n"
                                      "                    {text-align : center;\n"
                                      "                     color:gray;\n"
                                      "                     font: bold;\n"
                                      "                     border-radius:10px;\n"
                                      "                     border-top-color: #888888;\n"
                                      "                     border-left-color: #888888;\n"
                                      "                     border-right-color: #CCCCCC;\n"
                                      "                     border-bottom-color: #CCCCCC;\n"
                                      "                     border-top-width:2px;\n"
                                      "                     border-left-width:3px;\n"
                                      "                     border-right-width:3px;\n"
                                      "                     border-bottom-width:4px;\n"
                                      "                     border-style: outset;\n"
                                      "                     font : 14px;}\n"
                                      "                     QPushButton:pressed\n"
                                      "                     {text-align : center;\n"
                                      "                      background-color : light gray;\n"
                                      "                      font: bold;\n"
                                      "                      border-top-color: #888888;\n"
                                      "                      border-left-color: #888888;\n"
                                      "                      border-right-color: #CCCCCC;\n"
                                      "                      border-bottom-color: #CCCCCC;\n"
                                      "                      border-width: 2px;\n"
                                      "                      border-style: outset;\n"
                                      "                      font : 14px;}\n"
                                      "\n"
                                      "")
        self.verticalLayout.addWidget(self.pushButton)
        self.gridLayout.addLayout(self.verticalLayout, 3, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 60))
        self.lineEdit.setStyleSheet("border-radius:10px;background-color: rgb(255, 255, 255);border: 1px solid rgb(200, 200, 200)")
        self.gridLayout.addWidget(self.lineEdit, 0, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "型号名称："))
        self.pushButton_2.setText(_translate("Form", "本地上传图片"))
        self.pushButton_3.setText(_translate("Form", "流程拍摄录入"))
        self.pushButton.setText(_translate("Form", "确认"))

    #本地打开文件
    def openfile(self):
        image_file,_=QFileDialog.getOpenFileName(self,'Open file','','Image files (*.jpg *.gif *.png *.jpeg)')
        self.label_2.setPixmap(QPixmap(image_file))
        self.image =image_file

    #确认型号录入
    def ok(self):
        session = MySession()
        self.name = self.lineEdit.text()
        if self.name and self.image:
            t = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())
            result = session.query(Standard).filter(Standard.flag != 2,Standard.name ==self.name).first()
            if not result:
                session.add(Standard(name =self.name,url=self.image, created_time=t,flag=0))
                session.commit()
                self.image=''
                self.lineEdit.clear()
                self.label_2.setPixmap(QPixmap(''))
            else:
                reply = QMessageBox.information(self, '信息', '该型号已存在！',
                                                QMessageBox.Yes | QMessageBox.No)
        else:
            reply = QMessageBox.information(self, '信息', '信息填入不完整！',
                                            QMessageBox.Yes | QMessageBox.No)


class F(object):
    def setupUi(self, Form):
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.widget = QtWidgets.QWidget()
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.tab3 = QWebEngineView(self.widget)
        self.channel2 = QWebChannel()
        self.printer2 = Print2()
        self.printer2.changeList2.connect(self.get_mes)
        self.channel2.registerObject('printer2', self.printer2)
        self.tab3.page().setWebChannel(self.channel2)
        self.tab3.load(QUrl("file:///./templete.html"))
        self.gridLayout_2.addWidget(self.tab3, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))


    #模板型号搜索删除
    def get_mes(self,e):
        session = MySession()
        if e[1] != '':
            reply = QMessageBox.information(self, '提示', '删除后无法恢复!',
                                            QMessageBox.Yes | QMessageBox.No)
            if reply == QMessageBox.Yes:
                try:
                    session.query(Standard).filter(Standard.id == int(e[1])).update({Standard.flag: 2},synchronize_session=False)
                    session.commit()
                    lists = session.query(Standard).filter(Standard.flag != 2,Standard.name.like("%" + e[0] + "%")).all()
                    lists = [x.to_dict() for x in lists]
                    self.his.page().runJavaScript("window.uptext('{}')".format(json.dumps(lists)))
                except:
                    session.close()
        else:
            lists = session.query(Standard).filter(Standard.flag != 2,Standard.name.like("%" + e[0] + "%")).all()
            lists = [x.to_dict() for x in lists]
            self.tab3.page().runJavaScript("window.uptext('{}')".format(json.dumps(lists)))
            session.close()


class FramePage1(QWidget, A):
    def __init__(self):
        super().__init__()
        self.setupUi(self)


class FramePage2(QWidget, B):
    def __init__(self):
        super().__init__()
        self.setupUi(self)


class FramePage3(QWidget, C):
    def __init__(self):
        super().__init__()
        self.setupUi(self)


class FramePage4(QWidget, D):
    def __init__(self):
        super().__init__()
        self.setupUi(self)


class FramePage5(QWidget, E):
    def __init__(self):
        super().__init__()
        self.setupUi(self)


class FramePage6(QWidget, F):
    def __init__(self):
        super().__init__()
        self.setupUi(self)


class Ui_Form(QWidget):
    t1 = Worker(tag=3)
    timer = QTimer()
    def __init__(self):
        super().__init__()
        self.setupUi()
        self.t1.breakSignals.connect(self.getchart)
        self.qsl = QStackedLayout(self.frame_2)
        # 实例化分页面
        self.Page1 = FramePage1()
        self.Page2 = FramePage2()
        self.Page3 = FramePage3()
        self.Page4 = FramePage4()
        self.Page5 = FramePage5()
        self.Page6 = FramePage6()
        # 加入到布局中
        self.qsl.addWidget(self.Page1)
        self.qsl.addWidget(self.Page2)
        self.qsl.addWidget(self.Page3)
        self.qsl.addWidget(self.Page4)
        self.qsl.addWidget(self.Page5)
        self.qsl.addWidget(self.Page6)
        # 控制函数
        self.controller()

    def controller(self):
        self.pushButton.clicked.connect(self.switch)
        self.pushButton_2.clicked.connect(self.switch)
        self.pushButton_4.clicked.connect(self.switch)
        self.pushButton_5.clicked.connect(self.switch)
        self.pushButton_6.clicked.connect(self.switch)
        self.pushButton_10.clicked.connect(self.switch)
        self.pushButton_11.clicked.connect(self.switch)
        self.pushButton_12.clicked.connect(self.switch)
        self.pushButton_13.clicked.connect(self.switch)
        self.pushButton_14.clicked.connect(self.switch)
        self.pushButton_15.clicked.connect(self.switch)

    def switch(self):
        sender = self.sender().objectName()
        index = {
            "Page0": 0,
            "Page1": 1,
            "Page2_0": 2,
            "Page2_1": 2,
            "Page2_2": 2,
            "Page2_3": 2,
            "Page2_4": 2,
            "Page2_5": 2,
            "Page3":3,
            "Page4":4,
            "Page5": 5,
        }
        # if index[sender] ==2:
        #     self.frame_4.setVisible(False)
        self.qsl.setCurrentIndex(index[sender])

    def setupUi(self):
        self.resize(1550, 900)
        self.setBaseSize(QtCore.QSize(0, 0))
        self.timer.timeout.connect(self.change_today)
        self.timer.start(1000)
        self.gridLayout = QtWidgets.QGridLayout(self)
        self.gridLayout.setSpacing(0)
        self.frame_2 = QtWidgets.QFrame(self)
        self.frame_2.setMinimumSize(QtCore.QSize(800, 0))
        self.frame_2.setStyleSheet("background-color: rgb(255, 250, 240);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setLineWidth(1)
        self.gridLayout.addWidget(self.frame_2, 0, 0, 2, 1)
        self.frame = QtWidgets.QFrame(self)
        self.frame.setMinimumSize(QtCore.QSize(400, 600))
        self.frame.setMaximumSize(QtCore.QSize(450, 16777215))
        self.frame.setStyleSheet("background-color: rgb(255, 253, 249);\n"
                                 "border-top-right-radius:10px;\n"
                                 "border-top-left-radius:10px")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(1)
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setVisible(False)
        self.frame_4.setMinimumSize(QtCore.QSize(110, 0))
        self.frame_4.setMaximumSize(QtCore.QSize(130, 16777215))
        self.frame_4.setStyleSheet("background-color: rgb(248, 251, 255);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.pushButton_15 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_15.setMinimumSize(QtCore.QSize(90, 40))
        self.pushButton_15.setStyleSheet("QPushButton\n"
                                         "                    {text-align : center;\n"
                                         "                     color:gray;\n"
                                         "                     font: bold;\n"
                                         "                     border-radius:10px;\n"
                                         "                     border-top-color: #888888;\n"
                                         "                     border-left-color: #888888;\n"
                                         "                     border-right-color: #CCCCCC;\n"
                                         "                     border-bottom-color: #CCCCCC;\n"
                                         "                     border-top-width:2px;\n"
                                         "                     border-left-width:3px;\n"
                                         "                     border-right-width:3px;\n"
                                         "                     border-bottom-width:4px;\n"
                                         "                     background-color:qlineargradient(x1:0, y1:0, x2:0, y2:1, stop: 0 #E5E5E5, stop: 1 #B7B7B7);\n"
                                         "                     background-color: rgb(255, 254, 249);\n"
                                         "                     border-style: outset;\n"
                                         "                     font : 14px;}\n"
                                         "                     QPushButton:pressed\n"
                                         "                     {text-align : center;\n"
                                         "                      background-color : light gray;\n"
                                         "                      font: bold;\n"
                                         "                      border-top-color: #888888;\n"
                                         "                      border-left-color: #888888;\n"
                                         "                      border-right-color: #CCCCCC;\n"
                                         "                      border-bottom-color: #CCCCCC;\n"
                                         "                      border-width: 2px;\n"
                                         "                      border-style: outset;\n"
                                         "                      font : 14px;}\n"
                                         "\n"
                                         "")
        self.pushButton_15.setIconSize(QtCore.QSize(20, 20))
        self.gridLayout_5.addWidget(self.pushButton_15, 5, 0, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_14.setMinimumSize(QtCore.QSize(90, 40))
        self.pushButton_14.setStyleSheet("QPushButton\n"
                                         "                    {text-align : center;\n"
                                         "                     color:gray;\n"
                                         "                     font: bold;\n"
                                         "                     border-radius:10px;\n"
                                         "                     border-top-color: #888888;\n"
                                         "                     border-left-color: #888888;\n"
                                         "                     border-right-color: #CCCCCC;\n"
                                         "                     border-bottom-color: #CCCCCC;\n"
                                         "                     border-top-width:2px;\n"
                                         "                     border-left-width:3px;\n"
                                         "                     border-right-width:3px;\n"
                                         "                     border-bottom-width:4px;\n"
                                         "                     background-color:qlineargradient(x1:0, y1:0, x2:0, y2:1, stop: 0 #E5E5E5, stop: 1 #B7B7B7);\n"
                                         "                     background-color: rgb(255, 254, 249);\n"
                                         "                     border-style: outset;\n"
                                         "                     font : 14px;}\n"
                                         "                     QPushButton:pressed\n"
                                         "                     {text-align : center;\n"
                                         "                      background-color : light gray;\n"
                                         "                      font: bold;\n"
                                         "                      border-top-color: #888888;\n"
                                         "                      border-left-color: #888888;\n"
                                         "                      border-right-color: #CCCCCC;\n"
                                         "                      border-bottom-color: #CCCCCC;\n"
                                         "                      border-width: 2px;\n"
                                         "                      border-style: outset;\n"
                                         "                      font : 14px;}\n"
                                         "\n"
                                         "")
        self.pushButton_14.setIconSize(QtCore.QSize(20, 20))
        self.gridLayout_5.addWidget(self.pushButton_14, 4, 0, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_11.setMinimumSize(QtCore.QSize(90, 40))
        self.pushButton_11.setStyleSheet("QPushButton\n"
                                         "                    {text-align : center;\n"
                                         "                     color:gray;\n"
                                         "                     font: bold;\n"
                                         "                     border-radius:10px;\n"
                                         "                     border-top-color: #888888;\n"
                                         "                     border-left-color: #888888;\n"
                                         "                     border-right-color: #CCCCCC;\n"
                                         "                     border-bottom-color: #CCCCCC;\n"
                                         "                     border-top-width:2px;\n"
                                         "                     border-left-width:3px;\n"
                                         "                     border-right-width:3px;\n"
                                         "                     border-bottom-width:4px;\n"
                                         "                     background-color:qlineargradient(x1:0, y1:0, x2:0, y2:1, stop: 0 #E5E5E5, stop: 1 #B7B7B7);\n"
                                         "                     background-color: rgb(255, 254, 249);\n"
                                         "                     border-style: outset;\n"
                                         "                     font : 14px;}\n"
                                         "                     QPushButton:pressed\n"
                                         "                     {text-align : center;\n"
                                         "                      background-color : light gray;\n"
                                         "                      font: bold;\n"
                                         "                      border-top-color: #888888;\n"
                                         "                      border-left-color: #888888;\n"
                                         "                      border-right-color: #CCCCCC;\n"
                                         "                      border-bottom-color: #CCCCCC;\n"
                                         "                      border-width: 2px;\n"
                                         "                      border-style: outset;\n"
                                         "                      font : 14px;}\n"
                                         "\n"
                                         "")
        self.pushButton_11.setIconSize(QtCore.QSize(20, 20))
        self.gridLayout_5.addWidget(self.pushButton_11, 1, 0, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_13.setMinimumSize(QtCore.QSize(90, 40))
        self.pushButton_13.setStyleSheet("QPushButton\n"
                                         "                    {text-align : center;\n"
                                         "                     color:gray;\n"
                                         "                     font: bold;\n"
                                         "                     border-radius:10px;\n"
                                         "                     border-top-color: #888888;\n"
                                         "                     border-left-color: #888888;\n"
                                         "                     border-right-color: #CCCCCC;\n"
                                         "                     border-bottom-color: #CCCCCC;\n"
                                         "                     border-top-width:2px;\n"
                                         "                     border-left-width:3px;\n"
                                         "                     border-right-width:3px;\n"
                                         "                     border-bottom-width:4px;\n"
                                         "                     background-color:qlineargradient(x1:0, y1:0, x2:0, y2:1, stop: 0 #E5E5E5, stop: 1 #B7B7B7);\n"
                                         "                     background-color: rgb(255, 254, 249);\n"
                                         "                     border-style: outset;\n"
                                         "                     font : 14px;}\n"
                                         "                     QPushButton:pressed\n"
                                         "                     {text-align : center;\n"
                                         "                      background-color : light gray;\n"
                                         "                      font: bold;\n"
                                         "                      border-top-color: #888888;\n"
                                         "                      border-left-color: #888888;\n"
                                         "                      border-right-color: #CCCCCC;\n"
                                         "                      border-bottom-color: #CCCCCC;\n"
                                         "                      border-width: 2px;\n"
                                         "                      border-style: outset;\n"
                                         "                      font : 14px;}\n"
                                         "\n"
                                         "")
        self.pushButton_13.setIconSize(QtCore.QSize(20, 20))
        self.gridLayout_5.addWidget(self.pushButton_13, 3, 0, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_12.setMinimumSize(QtCore.QSize(90, 40))
        self.pushButton_12.setStyleSheet("QPushButton\n"
                                         "                    {text-align : center;\n"
                                         "                     color:gray;\n"
                                         "                     font: bold;\n"
                                         "                     border-radius:10px;\n"
                                         "                     border-top-color: #888888;\n"
                                         "                     border-left-color: #888888;\n"
                                         "                     border-right-color: #CCCCCC;\n"
                                         "                     border-bottom-color: #CCCCCC;\n"
                                         "                     border-top-width:2px;\n"
                                         "                     border-left-width:3px;\n"
                                         "                     border-right-width:3px;\n"
                                         "                     border-bottom-width:4px;\n"
                                         "                     background-color:qlineargradient(x1:0, y1:0, x2:0, y2:1, stop: 0 #E5E5E5, stop: 1 #B7B7B7);\n"
                                         "                     background-color: rgb(255, 254, 249);\n"
                                         "                     border-style: outset;\n"
                                         "                     font : 14px;}\n"
                                         "                     QPushButton:pressed\n"
                                         "                     {text-align : center;\n"
                                         "                      background-color : light gray;\n"
                                         "                      font: bold;\n"
                                         "                      border-top-color: #888888;\n"
                                         "                      border-left-color: #888888;\n"
                                         "                      border-right-color: #CCCCCC;\n"
                                         "                      border-bottom-color: #CCCCCC;\n"
                                         "                      border-width: 2px;\n"
                                         "                      border-style: outset;\n"
                                         "                      font : 14px;}\n"
                                         "\n"
                                         "")
        self.pushButton_12.setIconSize(QtCore.QSize(20, 20))
        self.gridLayout_5.addWidget(self.pushButton_12, 2, 0, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_10.setMinimumSize(QtCore.QSize(90, 40))
        self.pushButton_10.setStyleSheet("QPushButton\n"
                                         "                    {text-align : center;\n"
                                         "                     color:gray;\n"
                                         "                     font: bold;\n"
                                         "                     border-radius:10px;\n"
                                         "                     border-top-color: #888888;\n"
                                         "                     border-left-color: #888888;\n"
                                         "                     border-right-color: #CCCCCC;\n"
                                         "                     border-bottom-color: #CCCCCC;\n"
                                         "                     border-top-width:2px;\n"
                                         "                     border-left-width:3px;\n"
                                         "                     border-right-width:3px;\n"
                                         "                     border-bottom-width:4px;\n"
                                         "                     background-color:qlineargradient(x1:0, y1:0, x2:0, y2:1, stop: 0 #E5E5E5, stop: 1 #B7B7B7);\n"
                                         "                     background-color: rgb(255, 254, 249);\n"
                                         "                     border-style: outset;\n"
                                         "                     font : 14px;}\n"
                                         "                     QPushButton:pressed\n"
                                         "                     {text-align : center;\n"
                                         "                      background-color : light gray;\n"
                                         "                      font: bold;\n"
                                         "                      border-top-color: #888888;\n"
                                         "                      border-left-color: #888888;\n"
                                         "                      border-right-color: #CCCCCC;\n"
                                         "                      border-bottom-color: #CCCCCC;\n"
                                         "                      border-width: 2px;\n"
                                         "                      border-style: outset;\n"
                                         "                      font : 14px;}\n"
                                         "\n"
                                         "")
        self.pushButton_10.setIconSize(QtCore.QSize(20, 20))
        self.gridLayout_5.addWidget(self.pushButton_10, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_4, 0, 0, 2, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setStyleSheet("background-color: rgb(255, 244, 247);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setStyleSheet("background-color: rgb(255, 244, 247);\n"
                                   "border-top-right-radius:0px;\n"
                                   "border-top-left-radius:0px")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_2.setPixmap(QPixmap('./icon/good2.png'))
        self.label_2.setAlignment(Qt.AlignCenter)
        self.horizontalLayout_3.addWidget(self.label_2)
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setAlignment(Qt.AlignCenter)
        self.horizontalLayout_3.addWidget(self.label_5)
        self.gridLayout_6.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setPixmap(QPixmap('./icon/bad2.png'))
        self.label_3.setAlignment(Qt.AlignCenter)
        self.label_3.setMaximumSize(QtCore.QSize(150, 16777215))
        self.horizontalLayout_4.addWidget(self.label_3)
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        self.label_6.setAlignment(Qt.AlignCenter)
        self.horizontalLayout_4.addWidget(self.label_6)
        self.gridLayout_6.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setStyleSheet("background-color: rgb(255, 237, 235);\n"
                                   "border: 1px solid #EDEDED;\n"
                                   ";border-radius: 10px;\n"
                                   "padding:3px")
        self.label_4.setAlignment(Qt.AlignCenter)
        self.gridLayout_6.addWidget(self.label_4, 2, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_3, 1, 1, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(5, 5, 5, 30)
        self.gridLayout_2.setHorizontalSpacing(12)
        self.gridLayout_2.setVerticalSpacing(40)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setMinimumSize(QtCore.QSize(110, 40))
        self.pushButton_3.setStyleSheet("QPushButton\n"
                                        "                    {text-align : center;\n"
                                        "                     color:gray;\n"
                                        "                     font: bold;\n"
                                        "                     border-radius:10px;\n"
                                        "                     border-top-color: #888888;\n"
                                        "                     border-left-color: #888888;\n"
                                        "                     border-right-color: #CCCCCC;\n"
                                        "                     border-bottom-color: #CCCCCC;\n"
                                        "                     border-top-width:2px;\n"
                                        "                     border-left-width:3px;\n"
                                        "                     border-right-width:3px;\n"
                                        "                     border-bottom-width:4px;\n"
                                        "                     background-color:qlineargradient(x1:0, y1:0, x2:0, y2:1, stop: 0 #E5E5E5, stop: 1 #B7B7B7);\n"
                                        "                     background-color: rgb(255, 254, 249);\n"
                                        "                     border-style: outset;\n"
                                        "                     font : 14px;}\n"
                                        "                     QPushButton:pressed\n"
                                        "                     {text-align : center;\n"
                                        "                      background-color : light gray;\n"
                                        "                      font: bold;\n"
                                        "                      border-top-color: #888888;\n"
                                        "                      border-left-color: #888888;\n"
                                        "                      border-right-color: #CCCCCC;\n"
                                        "                      border-bottom-color: #CCCCCC;\n"
                                        "                      border-width: 2px;\n"
                                        "                      border-style: outset;\n"
                                        "                      font : 14px;}\n"
                                        "\n"
                                        "")
        self.pushButton_3.setIconSize(QtCore.QSize(20, 20))
        self.gridLayout_2.addWidget(self.pushButton_3, 2, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setMinimumSize(QtCore.QSize(110, 40))
        self.pushButton_5.setStyleSheet("QPushButton\n"
                                        "                    {text-align : center;\n"
                                        "                     color:gray;\n"
                                        "                     border-radius:10px;\n"
                                        "                     font: bold;\n"
                                        "                     border-top-color: #888888;\n"
                                        "                     border-left-color: #888888;\n"
                                        "                     border-right-color: #CCCCCC;\n"
                                        "                     border-bottom-color: #CCCCCC;\n"
                                        "                     border-top-width:2px;\n"
                                        "                     border-left-width:3px;\n"
                                        "                     border-right-width:3px;\n"
                                        "                     border-bottom-width:4px;\n"
                                        "                     background-color:qlineargradient(x1:0, y1:0, x2:0, y2:1, stop: 0 #E5E5E5, stop: 1 #B7B7B7);\n"
                                        "                     background-color: rgb(255, 254, 249);\n"
                                        "                     border-style: outset;\n"
                                        "                     font : 14px;}\n"
                                        "                     QPushButton:pressed\n"
                                        "                     {text-align : center;\n"
                                        "                      background-color : light gray;\n"
                                        "                      font: bold;\n"
                                        "                      border-top-color: #888888;\n"
                                        "                      border-left-color: #888888;\n"
                                        "                      border-right-color: #CCCCCC;\n"
                                        "                      border-bottom-color: #CCCCCC;\n"
                                        "                      border-width: 2px;\n"
                                        "                      border-style: outset;\n"
                                        "                      font : 14px;}\n"
                                        "\n"
                                        "")
        self.pushButton_5.setIconSize(QtCore.QSize(20, 20))
        self.gridLayout_2.addWidget(self.pushButton_5, 1, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setMinimumSize(QtCore.QSize(110, 40))
        self.pushButton.setStyleSheet("QPushButton\n"
                                      "                    {text-align : center;\n"
                                      "                     color:gray;\n"
                                      "                     border-radius:10px;\n"
                                      "                     font: bold;\n"
                                      "                     border-top-color: #888888;\n"
                                      "                     border-left-color: #888888;\n"
                                      "                     border-right-color: #CCCCCC;\n"
                                      "                     border-bottom-color: #CCCCCC;\n"
                                      "                     border-top-width:2px;\n"
                                      "                     border-left-width:3px;\n"
                                      "                     border-right-width:3px;\n"
                                      "                     border-bottom-width:4px;\n"
                                      "                     background-color:qlineargradient(x1:0, y1:0, x2:0, y2:1, stop: 0 #E5E5E5, stop: 1 #B7B7B7);\n"
                                      "                     background-color: rgb(255, 254, 249);\n"
                                      "                     border-style: outset;\n"
                                      "                     font : 14px;}\n"
                                      "                     QPushButton:pressed\n"
                                      "                     {text-align : center;\n"
                                      "                      background-color : light gray;\n"
                                      "                      font: bold;\n"
                                      "                      border-top-color: #888888;\n"
                                      "                      border-left-color: #888888;\n"
                                      "                      border-right-color: #CCCCCC;\n"
                                      "                      border-bottom-color: #CCCCCC;\n"
                                      "                      border-width: 2px;\n"
                                      "                      border-style: outset;\n"
                                      "                      font : 14px;}\n"
                                      "\n"
                                      "")
        self.pushButton.setIconSize(QtCore.QSize(20, 20))
        self.gridLayout_2.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setMinimumSize(QtCore.QSize(110, 40))
        self.pushButton_4.setStyleSheet("QPushButton\n"
                                        "                    {text-align : center;\n"
                                        "                     color:gray;\n"
                                        "                     font: bold;\n"
                                        "                     border-radius:10px;\n"
                                        "                     border-top-color: #888888;\n"
                                        "                     border-left-color: #888888;\n"
                                        "                     border-right-color: #CCCCCC;\n"
                                        "                     border-bottom-color: #CCCCCC;\n"
                                        "                     border-top-width:2px;\n"
                                        "                     border-left-width:3px;\n"
                                        "                     border-right-width:3px;\n"
                                        "                     border-bottom-width:4px;\n"
                                        "                     background-color:qlineargradient(x1:0, y1:0, x2:0, y2:1, stop: 0 #E5E5E5, stop: 1 #B7B7B7);\n"
                                        "                     background-color: rgb(255, 254, 249);\n"
                                        "                     border-style: outset;\n"
                                        "                     font : 14px;}\n"
                                        "                     QPushButton:pressed\n"
                                        "                     {text-align : center;\n"
                                        "                      background-color : light gray;\n"
                                        "                      font: bold;\n"
                                        "                      border-top-color: #888888;\n"
                                        "                      border-left-color: #888888;\n"
                                        "                      border-right-color: #CCCCCC;\n"
                                        "                      border-bottom-color: #CCCCCC;\n"
                                        "                      border-width: 2px;\n"
                                        "                      border-style: outset;\n"
                                        "                      font : 14px;}\n"
                                        "\n"
                                        "")
        self.pushButton_4.setIconSize(QtCore.QSize(20, 20))
        self.gridLayout_2.addWidget(self.pushButton_4, 0, 1, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame)
        self.pushButton_6.setMinimumSize(QtCore.QSize(110, 40))
        self.pushButton_6.setStyleSheet("QPushButton\n"
                                        "                    {text-align : center;\n"
                                        "                     color:gray;\n"
                                        "                     font: bold;\n"
                                        "                     border-radius:10px;\n"
                                        "                     border-top-color: #888888;\n"
                                        "                     border-left-color: #888888;\n"
                                        "                     border-right-color: #CCCCCC;\n"
                                        "                     border-bottom-color: #CCCCCC;\n"
                                        "                     border-top-width:2px;\n"
                                        "                     border-left-width:3px;\n"
                                        "                     border-right-width:3px;\n"
                                        "                     border-bottom-width:4px;\n"
                                        "                     background-color:qlineargradient(x1:0, y1:0, x2:0, y2:1, stop: 0 #E5E5E5, stop: 1 #B7B7B7);\n"
                                        "                     background-color: rgb(255, 254, 249);\n"
                                        "                     border-style: outset;\n"
                                        "                     font : 14px;}\n"
                                        "                     QPushButton:pressed\n"
                                        "                     {text-align : center;\n"
                                        "                      background-color : light gray;\n"
                                        "                      font: bold;\n"
                                        "                      border-top-color: #888888;\n"
                                        "                      border-left-color: #888888;\n"
                                        "                      border-right-color: #CCCCCC;\n"
                                        "                      border-bottom-color: #CCCCCC;\n"
                                        "                      border-width: 2px;\n"
                                        "                      border-style: outset;\n"
                                        "                      font : 14px;}\n"
                                        "\n"
                                        "")
        self.pushButton_6.setIconSize(QtCore.QSize(20, 20))
        self.gridLayout_2.addWidget(self.pushButton_6, 2, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setMinimumSize(QtCore.QSize(110, 40))
        self.pushButton_2.setStyleSheet("QPushButton\n"
                                        "                    {text-align : center;\n"
                                        "                     color:gray;\n"
                                        "                     border-radius:10px;\n"
                                        "                     font: bold;\n"
                                        "                     border-top-color: #888888;\n"
                                        "                     border-left-color: #888888;\n"
                                        "                     border-right-color: #CCCCCC;\n"
                                        "                     border-bottom-color: #CCCCCC;\n"
                                        "                     border-top-width:2px;\n"
                                        "                     border-left-width:3px;\n"
                                        "                     border-right-width:3px;\n"
                                        "                     border-bottom-width:4px;\n"
                                        "                     background-color:qlineargradient(x1:0, y1:0, x2:0, y2:1, stop: 0 #E5E5E5, stop: 1 #B7B7B7);\n"
                                        "                     background-color: rgb(255, 254, 249);\n"
                                        "                     border-style: outset;\n"
                                        "                     font : 14px;}\n"
                                        "                     QPushButton:pressed\n"
                                        "                     {text-align : center;\n"
                                        "                      background-color : light gray;\n"
                                        "                      font: bold;\n"
                                        "                      border-top-color: #888888;\n"
                                        "                      border-left-color: #888888;\n"
                                        "                      border-right-color: #CCCCCC;\n"
                                        "                      border-bottom-color: #CCCCCC;\n"
                                        "                      border-width: 2px;\n"
                                        "                      border-style: outset;\n"
                                        "                      font : 14px;}\n"
                                        "\n"
                                        "")
        self.pushButton_2.setIconSize(QtCore.QSize(20, 20))
        self.gridLayout_2.addWidget(self.pushButton_2, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 1, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self)
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 250))
        self.frame_5.setBaseSize(QtCore.QSize(0, 0))
        self.frame_5.setStyleSheet("background-color: rgb(255, 253, 249);\n"
                                   "border-bottom-right-radius:10px;\n"
                                   "border-bottom-left-radius:10px;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_5)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.label = QtWidgets.QLabel(self.frame_5)
        self.label.setMinimumSize(QtCore.QSize(0, 50))
        self.label.setMaximumSize(QtCore.QSize(16777215, 60))
        self.label.setStyleSheet("color: rgb(255, 0, 0);")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.comboBox = QtWidgets.QComboBox(self.frame_5)
        self.comboBox.setStyleSheet("border-radius:4px;\n"
                                    "border: 1px solid rgb(200, 200, 200);")
        self.comboBox.setMinimumSize(QtCore.QSize(0, 36))
        self.horizontalLayout.addWidget(self.comboBox)
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_7.setMinimumSize(QtCore.QSize(80, 40))
        self.pushButton_7.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_7.setStyleSheet("QPushButton\n"
                                        "                    {text-align : center;\n"
                                        "                     color:gray;\n"
                                        "                     font: bold;\n"
                                        "                     border-radius:10px;\n"
                                        "                     border-top-color: #888888;\n"
                                        "                     border-left-color: #888888;\n"
                                        "                     border-right-color: #CCCCCC;\n"
                                        "                     border-bottom-color: #CCCCCC;\n"
                                        "                     border-top-width:2px;\n"
                                        "                     border-left-width:3px;\n"
                                        "                     border-right-width:3px;\n"
                                        "                     border-bottom-width:4px;\n"
                                        "                     background-color:qlineargradient(x1:0, y1:0, x2:0, y2:1, stop: 0 #E5E5E5, stop: 1 #B7B7B7);\n"
                                        "                     background-color: rgb(255, 254, 249);\n"
                                        "                     border-style: outset;\n"
                                        "                     font : 14px;}\n"
                                        "                     QPushButton:pressed\n"
                                        "                     {text-align : center;\n"
                                        "                      background-color : light gray;\n"
                                        "                      font: bold;\n"
                                        "                      border-top-color: #888888;\n"
                                        "                      border-left-color: #888888;\n"
                                        "                      border-right-color: #CCCCCC;\n"
                                        "                      border-bottom-color: #CCCCCC;\n"
                                        "                      border-width: 2px;\n"
                                        "                      border-style: outset;\n"
                                        "                      font : 14px;}\n"
                                        "\n"
                                        "")
        self.pushButton_7.setIconSize(QtCore.QSize(20, 20))
        self.horizontalLayout.addWidget(self.pushButton_7)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(12)
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_8.setMinimumSize(QtCore.QSize(110, 80))
        self.pushButton_8.setStyleSheet("QPushButton\n"
                                        "                    {text-align : center;\n"
                                        "                     color:gray;\n"
                                        "                     font: bold;\n"
                                        "                     border-radius:10px;\n"
                                        "                     border-top-color: #888888;\n"
                                        "                     border-left-color: #888888;\n"
                                        "                     border-right-color: #CCCCCC;\n"
                                        "                     border-bottom-color: #CCCCCC;\n"
                                        "                     border-top-width:2px;\n"
                                        "                     border-left-width:3px;\n"
                                        "                     border-right-width:3px;\n"
                                        "                     border-bottom-width:4px;\n"
                                        "                     background-color:qlineargradient(x1:0, y1:0, x2:0, y2:1, stop: 0 #E5E5E5, stop: 1 #B7B7B7);\n"
                                        "                     background-color: rgb(255, 254, 249);\n"
                                        "                     border-style: outset;\n"
                                        "                     font : 14px;}\n"
                                        "                     QPushButton:pressed\n"
                                        "                     {text-align : center;\n"
                                        "                      background-color : light gray;\n"
                                        "                      font: bold;\n"
                                        "                      border-top-color: #888888;\n"
                                        "                      border-left-color: #888888;\n"
                                        "                      border-right-color: #CCCCCC;\n"
                                        "                      border-bottom-color: #CCCCCC;\n"
                                        "                      border-width: 2px;\n"
                                        "                      border-style: outset;\n"
                                        "                      font : 14px;}\n"
                                        "\n"
                                        "")
        self.pushButton_8.setIconSize(QtCore.QSize(20, 20))
        self.horizontalLayout_2.addWidget(self.pushButton_8)
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_9.setMinimumSize(QtCore.QSize(110, 80))
        self.pushButton_9.setStyleSheet("QPushButton\n"
                                        "                    {text-align : center;\n"
                                        "                     color:gray;\n"
                                        "                     border-radius:10px;\n"
                                        "                     font: bold;\n"
                                        "                     border-top-color: #888888;\n"
                                        "                     border-left-color: #888888;\n"
                                        "                     border-right-color: #CCCCCC;\n"
                                        "                     border-bottom-color: #CCCCCC;\n"
                                        "                     border-top-width:2px;\n"
                                        "                     border-left-width:3px;\n"
                                        "                     border-right-width:3px;\n"
                                        "                     border-bottom-width:4px;\n"
                                        "                     background-color:qlineargradient(x1:0, y1:0, x2:0, y2:1, stop: 0 #E5E5E5, stop: 1 #B7B7B7);\n"
                                        "                     background-color: rgb(255, 254, 249);\n"
                                        "                     border-style: outset;\n"
                                        "                     font : 14px;}\n"
                                        "                     QPushButton:pressed\n"
                                        "                     {text-align : center;\n"
                                        "                      background-color : light gray;\n"
                                        "                      font: bold;\n"
                                        "                      border-top-color: #888888;\n"
                                        "                      border-left-color: #888888;\n"
                                        "                      border-right-color: #CCCCCC;\n"
                                        "                      border-bottom-color: #CCCCCC;\n"
                                        "                      border-width: 2px;\n"
                                        "                      border-style: outset;\n"
                                        "                      font : 14px;}\n"
                                        "\n"
                                        "")
        self.pushButton_9.setIconSize(QtCore.QSize(20, 20))
        self.horizontalLayout_2.addWidget(self.pushButton_9)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout_4.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_5, 1, 1, 1, 1)

        self.retranslateUi(self)
        self.pushButton.clicked.connect(self.lab1)
        self.pushButton_2.clicked.connect(self.lab2)
        self.pushButton_3.clicked.connect(self.lab7)
        self.pushButton_4.clicked.connect(self.lab4)
        self.pushButton_5.clicked.connect(self.lab5)
        self.pushButton_6.clicked.connect(self.lab6)
        self.pushButton_7.clicked.connect(self.check)
        self.pushButton_15.clicked.connect(lambda:self.lab3('所有'))
        self.pushButton_14.clicked.connect(lambda:self.lab3('类目5'))
        self.pushButton_13.clicked.connect(lambda:self.lab3('类目4'))
        self.pushButton_12.clicked.connect(lambda:self.lab3('类目3'))
        self.pushButton_11.clicked.connect(lambda:self.lab3('类目2'))
        self.pushButton_10.clicked.connect(lambda:self.lab3('类目1'))
        QtCore.QMetaObject.connectSlotsByName(self)
        self.get_types()

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "磁体缺陷视觉检测设备"))
        self.pushButton.setText(_translate("Form", "运行界面"))
        self.pushButton_2.setText(_translate("Form", "图表分析"))
        self.pushButton_3.setText(_translate("Form", "不良明细"))
        self.pushButton_4.setText(_translate("Form", "次品排名"))
        self.pushButton_5.setText(_translate("Form", "产品录入"))
        self.pushButton_6.setText(_translate("Form", "模板档案"))
        self.pushButton_7.setText(_translate("Form", "确认更换"))
        self.pushButton_8.setText(_translate("Form", "启动"))
        self.pushButton_9.setText(_translate("Form", "停止"))
        self.pushButton_15.setText(_translate("Form", "所有"))
        self.pushButton_14.setText(_translate("Form", "类目5"))
        self.pushButton_13.setText(_translate("Form", "类目4"))
        self.pushButton_12.setText(_translate("Form", "类目3"))
        self.pushButton_11.setText(_translate("Form", "类目2"))
        self.pushButton_10.setText(_translate("Form", "类目1"))
        self.pushButton.setObjectName("Page0")
        self.pushButton_2.setObjectName("Page1")
        self.pushButton_6.setObjectName("Page5")
        self.pushButton_5.setObjectName("Page4")
        self.pushButton_4.setObjectName("Page3")
        self.pushButton_10.setObjectName("Page2_0")
        self.pushButton_11.setObjectName("Page2_1")
        self.pushButton_12.setObjectName("Page2_2")
        self.pushButton_13.setObjectName("Page2_3")
        self.pushButton_14.setObjectName("Page2_4")
        self.pushButton_15.setObjectName("Page2_5")

    def lab7(self):
        self.frame_4.setVisible(True)

    def lab6(self,e):
        self.t1.Flag = False
        self.frame_4.setVisible(False)
        session = MySession()
        lists = session.query(Standard).filter(Standard.flag != 2).all()
        session.close()
        lists = [x.to_dict() for x in lists]
        self.Page6.tab3.page().runJavaScript("window.uptext('{}')".format(json.dumps(lists)))

    def lab5(self):
        self.t1.Flag = False

    def lab4(self):
        self.t1.Flag = False
        session = MySession()
        result =rank(session)
        session.close()
        self.Page4.tab3.page().runJavaScript("window.uptext('{}')".format(json.dumps(result)))

    def lab3(self,e):
        self.t1.Flag = False
        self.frame_4.setVisible(False)
        session = MySession()
        if e =='所有':
            lists = session.query(History).order_by(History.id.desc()).limit(2000)
            self.Page3.type = ''
        else:
            lists = session.query(History).filter(History.types == e).order_by(History.id.desc()).limit(2000)
            self.Page3.type = e
        session.close()
        lists = [x.to_dict() for x in lists]
        self.Page3.tab2.page().runJavaScript("window.uptext('{}','{}')".format(json.dumps(lists),e))

    def lab2(self,e):
        self.t1.Flag = True
        self.frame_4.setVisible(False)
        self.t1.start()

    def lab1(self):
        self.t1.Flag = False

    # 获取echarts数据
    def getchart(self, data):
        self.Page2.tab1.page().runJavaScript("window.updata('{}')".format(json.dumps(data)))

    #获取检测型号
    def get_types(self):
        names = session.query(Standard).filter(Standard.flag == 1).first()
        if names:
            self.label.setText("当前检测型号：" + names.name)
        else:
            self.label.setText("当前检测型号:")
        name = session.query(Standard.name).filter(Standard.flag != 2).all()
        name = [r for (r,) in name]
        self.comboBox.clear()
        self.comboBox.addItem('请选择型号')
        for i in name:
            self.comboBox.addItem(i)

    #更换检测型号
    def check(self):
        text = self.comboBox.currentText()
        if text != "请选择型号":
            session.query(Standard).filter(Standard.flag == 1).update({Standard.flag: 0}, synchronize_session=False)
            session.commit()
            session.query(Standard).filter(Standard.flag != 2, Standard.name == text).update({Standard.flag: 1}, synchronize_session=False)
            session.commit()
            self.label.setText("当前检测型号:" + text)
        else:
            pass

    #首页数量统计
    def change_today(self):
        all,good,bad =get_today()
        if all != 0:
            g ='%.2f' % (good * 100 / all)
            b ='%.2f' % (bad * 100 / all)
        else:
            g = '0.00'
            b ='0.00'
        self.label_5.setText("<font style = 'font-size:45px; color:#21b5b1; font-weight:bold'>"+str(good)+"</font>"
                             "<br/>""<br/>"
                             "<font style = 'font-size:20px; color:#21b5b1;'> 合格率"+str(g)+"%"+"</font>")
        self.label_6.setText("<font style = 'font-size:45px; color:#e4686e; font-weight:bold'>"+str(bad)+"</font>"
                             "<br/>""<br/>"
                             "<font style = 'font-size:20px; color:#e4686e;'> 次品率"+str(b)+"%"+"</font>")


@app.post('/result/')
async def result_mes(item:Item2):
    goodNum =100
    badNum=19
    t = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())
    form.label_4.setText("合格数：" + str(goodNum) + "   劣质数：" + str(badNum) +"\n"+"\n"+ "时间：" + str(t))
    # session1 = MySession()
    # badNum = item.ng_count
    # goodNum = item.total -badNum
    # t = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())
    # t1 = time.strftime("%Y-%m-%d", time.localtime())
    # result = defaultdict(lambda: defaultdict(list))
    # final=[]
    # if item.result !=[]:
    #     for items in item.result:
    #         session1.add(History(standard_name=item.standard_name,types=dic[items["class"]],url1=items["image"],created_time=t))
    #         result[dic[items['class']]]['image'].append(items['image'])
    #         final = [{'class': name, **{inner_names: inner_values for inner_names, inner_values in values.items()}} for
    #                  name, values in result.items()]
    #     # form.label_8.setText(str(final))
    #     form.label_8.setText("合格数："+str(goodNum)+"   劣质数："+str(badNum)+"   时间："+str(t))
    # else:
    #     # form.label_8.setText('')
    #     form.label_8.setText("合格数：" + str(goodNum) + "   劣质数：" + str(badNum) + "   时间：" + str(t))
    # data =session1.query(Dailydata).filter(Dailydata.standard_name==item.standard_name,Dailydata.created_time ==t1).first()
    # if data:
    #     session1.query(Dailydata).filter(Dailydata.standard_name==item.standard_name,Dailydata.created_time ==t1).update({Dailydata.badNum: Dailydata.badNum + badNum, Dailydata.goodNum: Dailydata.goodNum + goodNum},
    #              synchronize_session=False)
    #     session1.query(Dailydata2).update({Dailydata2.badNum: Dailydata2.badNum + badNum, Dailydata2.goodNum: Dailydata2.goodNum + goodNum},
    #              synchronize_session=False)
    # else:
    #     session1.add(Dailydata(standard_name=item.standard_name,badNum=badNum,goodNum=goodNum,created_time=t1))
    #     session1.query(Dailydata2).update({Dailydata2.badNum: Dailydata2.badNum + badNum, Dailydata2.goodNum: Dailydata2.goodNum + goodNum},
    #              synchronize_session=False)
    # if final !=[]:
    #     for i in final:
    #         query = session1.query(Baddata).filter(Baddata.created_time ==t1,Baddata.standard_name ==item.standard_name,Baddata.types ==i["class"]).first()
    #         if not query:
    #             session1.add(Baddata(standard_name=item.standard_name,types=i["class"],Num=len(i["image"]),created_time=t1))
    #         else:
    #             session1.query(Baddata).filter(Baddata.created_time ==t1,Baddata.standard_name ==item.standard_name,Baddata.types ==i["class"]).update({Baddata.Num: Baddata.Num+len(i["image"])}, synchronize_session=False)
    # try:
    #     session1.commit()
    #     session1.close()
    # except:
    #     session1.close()
    #     print('数据入库失败')
    return {"status":200}


@app.post('/imgs/')
async def get_imgs(item:Item1):
    width =form.Page1.label.width()
    height =form.Page1.label.height()
    jpg = QPixmap(item.value).scaled(width, height-10)
    if item.key ==1:
        form.Page1.label.setPixmap(jpg)
    elif item.key ==2:
        form.Page1.label_2.setPixmap(jpg)
    elif item.key ==3:
        form.Page1.label_3.setPixmap(jpg)
    elif item.key ==4:
        form.Page1.label_4.setPixmap(jpg)
    elif item.key ==5:
        form.Page1.label_5.setPixmap(jpg)
    else:
        form.Page1.label_6.setPixmap(jpg)
    return {"status":200}


def start_server():
    import uvicorn
    uvicorn.run(app=app,
                host="127.0.0.1",
                port=8080,
                workers=1)


server_thread=threading.Thread(target=start_server)
server_thread.setDaemon(True)
server_thread.start()


if __name__ == "__main__":
    app = QApplication(sys.argv)
    form = Ui_Form()
    form.show()
    # form.showMaximized()
    sys.exit(app.exec_())